version: '3.8'
services:
  web:
    build: .
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py runserver_plus 0.0.0.0:8000 &
        daphne -b 0.0.0.0 -p 8001 linguaglow.asgi:application
      "
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - DJANGO_SETTINGS_MODULE=linguaglow.settings
    depends_on:
      - db
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=your_db_name
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U your_db_user"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  postgres_data: