# Generated by Django 5.1.4 on 2025-02-11 16:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="article",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="audio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("audio_url", models.URLField()),
                ("transcript", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="dialogue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lines", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="essay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.TextField()),
                ("conditions", models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="fillInTheBlanks",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Fill In The Blanks", max_length=255),
                ),
                ("text", models.TextField()),
                (
                    "display_format",
                    models.CharField(
                        choices=[
                            ("with_list", "With list"),
                            ("without_list", "Without list"),
                        ],
                        default="with_list",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="image",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image_url", models.URLField()),
                ("caption", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="imageUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image_url", models.URLField(unique=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="makeASentence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="Make A Sentence", max_length=255)),
                ("sentences", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="matchUpTheWords",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Match Up The Words", max_length=255),
                ),
                ("pairs", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="note",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="Note", max_length=255)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="sortIntoColumns",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Sort Into Columns", max_length=255),
                ),
                ("columns", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="test",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("time", models.PositiveIntegerField(null=True)),
                ("questions", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="trueOrFalse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("statements", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="unscramble",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="Unscramble", max_length=255)),
                ("words", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="wordList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="Word List", max_length=255)),
                ("words", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="wordSearch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("grid", models.JSONField()),
                ("words", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "student_level",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("elementary", "Elementary"),
                            ("pre_intermediate", "Pre-Intermediate"),
                            ("intermediate", "Intermediate"),
                            ("upper_intermediate", "Upper-Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="starter",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="labelImageOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "image_usage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hub.imageusage"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="labelImages",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("labels", models.JSONField()),
                (
                    "image_urls",
                    models.ManyToManyField(
                        related_name="label_images",
                        through="hub.labelImageOrder",
                        to="hub.imageusage",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="labelimageorder",
            name="label_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hub.labelimages"
            ),
        ),
        migrations.CreateModel(
            name="lesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("lexical_topics", models.TextField(blank=True, null=True)),
                ("grammar_topics", models.TextField(blank=True, null=True)),
                ("extra_topics", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="hub.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="section",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("topic", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField()),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="hub.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("object_id", models.UUIDField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="hub.section",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
