# Generated by Django 5.1.4 on 2025-01-06 20:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('student_level', models.CharField(choices=[('starter', 'Starter'), ('elementary', 'Elementary'), ('pre_intermediate', 'Pre-Intermediate'), ('intermediate', 'Intermediate'), ('upper_intermediate', 'Upper-Intermediate'), ('advanced', 'Advanced')], default='starter', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('lexical_topics', models.TextField(blank=True, null=True)),
                ('grammar_topics', models.TextField(blank=True, null=True)),
                ('extra_topics', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='hub.course')),
            ],
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='hub.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('wordList', 'Список слов'), ('matchUpTheWords', 'Соотнести слово с переводом'), ('essay', 'Эссе'), ('note', 'Заметка'), ('image', 'Картинка'), ('sortIntoColumns', 'Распределить по колонкам'), ('makeASentence', 'Составить предложение в правильном порядке'), ('unscramble', 'Составить слово'), ('fillInTheBlanksFromTheList', 'Заполнить пропуски словами из списка'), ('fillInTheBlanksWithSuitableWords', 'Заполнить пропуски подходящими словами'), ('dialogue', 'Диалог'), ('article', 'Статья'), ('audio', 'Аудио'), ('test', 'Тест'), ('trueOrFalse', 'Правда или ложь'), ('labelThePicture', 'Подписать картинку'), ('wordSearch', 'Филворд')], max_length=50)),
                ('order', models.PositiveIntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='hub.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
