# Generated by Django 5.1.4 on 2025-01-10 17:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_course_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='wordList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('words', models.JSONField()),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='word_list', to='hub.task')),
            ],
        ),
    ]
