# Generated by Django 5.1.4 on 2025-02-14 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0002_embeddedtask"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="time",
        ),
    ]
