# Generated by Django 5.1.4 on 2025-01-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_wordlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
