# Generated by Django 5.1.4 on 2025-01-11 18:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_alter_task_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='matchUpTheWords',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('words', models.JSONField()),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_up_the_words', to='hub.task')),
            ],
        ),
    ]
