# Generated by Django 5.1.4 on 2025-01-12 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_matchupthewords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='section',
        ),
        migrations.RemoveField(
            model_name='wordlist',
            name='task',
        ),
        migrations.AddField(
            model_name='wordlist',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wordlist',
            name='section',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_list', to='hub.section'),
        ),
        migrations.AddField(
            model_name='wordlist',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='matchUpTheWords',
        ),
        migrations.DeleteModel(
            name='task',
        ),
    ]
