# Generated by Django 5.1.4 on 2025-01-12 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_remove_task_section_remove_wordlist_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlist',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_list', to='hub.section'),
        ),
    ]
