# Generated by Django 5.1.4 on 2025-01-12 15:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hub', '0007_alter_wordlist_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='audio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_url', models.URLField()),
                ('transcript', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dialogue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lines', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='essay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='fillInTheBlanksFromTheList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('options', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='fillInTheBlanksWithSuitableWords',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='labelThePicture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('labels', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='makeASentence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('words', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='matchUpTheWords',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pairs', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='sortIntoColumns',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('columns', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('questions', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='trueOrFalse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statements', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='unscramble',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scrambled_word', models.CharField(max_length=255)),
                ('correct_word', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='wordSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grid', models.JSONField()),
                ('words', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='wordlist',
            name='order',
        ),
        migrations.RemoveField(
            model_name='wordlist',
            name='section',
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='hub.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
